#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable

layout(set = 0, binding = 0) uniform UBO {
    int16_t m1;
    i16vec4 m2;
};

layout(set = 1, binding = 0) buffer SSBO {
    int16_t mOut1;
    i16vec4 mOut2;
};

void main()
{
    mOut1 = -m1;
    mOut2 = -m2;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
