#version 450 core

#extension GL_EXT_shader_explicit_arithmetic_types_int8: enable

struct Buf
{
    int8_t  i8;
    i8vec2  i8v2;
    i8vec3  i8v3;
    i8vec4  i8v4;

} bufIn;

shared Buf buf[4];

layout(binding = 0) buffer BufOut
{
    i8vec4 i8v4;

} bufOut;

void main()
{
    uint i = gl_GlobalInvocationID.x % 4;

    switch (i)
    {
    case 0:
        bufOut.i8v4.x = buf[i].i8++;
        break;
    case 1:
        bufOut.i8v4.xy = buf[i].i8v2++;
        break;
    case 2:
        bufOut.i8v4.xyz = buf[i].i8v3++;
        break;
    case 3:
        bufOut.i8v4 = buf[i].i8v4++;
        break;
    }
}
// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
