#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable
#extension GL_AMD_gpu_shader_half_float : enable
#extension GL_ARB_gpu_shader_int64 : enable

layout(set = 0, binding = 0) uniform UBO {
    i16vec4 m1;
    u16vec4 m2;

    int16_t  m3;
    uint16_t m4;
};

layout(set = 1, binding = 0) buffer SSBO {
    i16vec4 mOut1;
    u16vec4 mOut2;
    ivec4   mOut3;
    uvec4   mOut4;
    i64vec4 mOut5;
    u64vec4 mOut6;
};

void main()
{
    mOut1 = i16vec4(m1) + i16vec4(m2);
    mOut2 = u16vec4(m2) + i16vec4(m1);

    mOut3 = ivec4(m1) + ivec4(m2);
    mOut4 = uvec4(m2) + uvec4(m1);

    mOut5 = i64vec4(m1) + i64vec4(m2);
    mOut6 = u64vec4(m2) + u64vec4(m1);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
