#version 450 core
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(set = 0, binding = 0) uniform UBO {
    int8_t m1;
    uint8_t m2;
};

layout(set = 1, binding = 0) buffer SSBO {
    int8_t mOut1;
    uint8_t mOut2;
    uint8_t mOut3;
};

void main()
{
    mOut1 = m1 >> 3;
    mOut2 = m2 >> 3;
    mOut3 = m1 << 3;
}
// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST

