#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable
#extension GL_ARB_gpu_shader_int64 : enable

layout(set = 0, binding = 0) uniform UBO {
    i16vec4 m1;
    u16vec4 m2;
    ivec4   m3;
    uvec4   m4;
    i64vec4 m5;
    u64vec4 m6;
};

layout(set = 1, binding = 0) buffer SSBO {
    i16vec4 mOut1;
    i16vec4 mOut2;
    i16vec4 mOut3;
    i16vec4 mOut4;
    i16vec4 mOut5;

    u16vec4 mOut6;
    u16vec4 mOut7;
    u16vec4 mOut8;
    u16vec4 mOut9;
    u16vec4 mOut10;
};

void main()
{
    mOut1  = i16vec4(m2);   // i16 <- u16
    mOut2  = i16vec4(m3);   // i16 <- i32
    mOut3  = i16vec4(m4);   // i16 <- u32
    mOut4  = i16vec4(m5);   // i16 <- i64
    mOut5  = i16vec4(m6);   // i16 <- u64

    mOut6  = u16vec4(m1);   // u16 <- i16
    mOut7  = u16vec4(m3);   // u16 <- i32
    mOut8  = u16vec4(m4);   // u16 <- u32
    mOut9  = u16vec4(m5);   // u16 <- i64
    mOut10 = u16vec4(m6);   // u16 <- u64
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
