#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable
#extension GL_ARB_gpu_shader_int64 : enable

layout(set = 0, binding = 0) uniform UBO {
    int      m1;
    int64_t  m2;
    uint     m3;
    uint64_t m4;
};

layout(set = 1, binding = 0) buffer SSBO {
    i16vec2 mOut1;
    i16vec4 mOut2;
    u16vec2 mOut3;
    u16vec4 mOut4;
};

void main()
{
    mOut1 = unpackInt2x16(m1);
    mOut2 = unpackInt4x16(m2);

    mOut3 = unpackUint2x16(m3);
    mOut4 = unpackUint4x16(m4);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
