#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable
#extension GL_AMD_gpu_shader_half_float : enable

layout(set = 0, binding = 0) uniform UBO {
    f16vec4 m1;
    vec4    m2;
    dvec4   m3;
};

layout(set = 1, binding = 0) buffer SSBO {
    i16vec4 mOut1;
    i16vec4 mOut2;
    i16vec4 mOut3;

    u16vec4 mOut4;
    u16vec4 mOut5;
    u16vec4 mOut6;
};

void main()
{
    mOut1 = i16vec4(m1);
    mOut2 = i16vec4(m2);
    mOut3 = i16vec4(m3);

    mOut4 = u16vec4(m1);
    mOut5 = u16vec4(m2);
    mOut6 = u16vec4(m3);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
