#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable
#extension GL_AMD_gpu_shader_half_float : enable

layout(set = 0, binding = 0) buffer SSBO1 {
    int16_t m1;
    int16_t m2;
    i16vec4 m3[64];
};

layout(set = 1, binding = 0) buffer SSBO2 {
    i16vec4 mOut;
};

void main()
{
    int16_t a = m1 + m2;
    i16vec4 b = m3[6];
    i16vec4 c = m3[int(a)];
    mOut = i16vec4(a) + b + c;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
