#version 450 core
#extension GL_AMD_gpu_shader_half_float : enable

layout(set = 0, binding = 0, std430, row_major) buffer UB
{
    f16mat2 um1;
};

layout(set = 0, binding = 1, std430, row_major) buffer BB
{
   f16mat2 bm1;
};

layout (local_size_x = 1) in;
void main()
{
    f16mat2 temp = um1;
    bm1 = temp;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
