#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable

layout(set = 0, binding = 0) uniform UBO {
    int16_t m1;
    int16_t m2;
    uint16_t m3;
    uint16_t m4;
    i16vec4 m5;
    i16vec4 m6;
    u16vec4 m7;
    u16vec4 m8;
};

layout(set = 1, binding = 0) buffer SSBO {
    int16_t mOut1;
    uint16_t mOut2;
    uint16_t mOut3;
    i16vec4 mOut4;
    u16vec4 mOut5;
    u16vec4 mOut6;
};

void main()
{
    int16_t  a = m1 & m2;
    uint16_t b = m2 & m3;
    uint16_t c = m3 & m4;

    i16vec4 va = m5 & m6;
    u16vec4 vb = m6 & m7;
    u16vec4 vc = m7 & m8;

    int16_t  d = m1 ^ a;
    uint16_t e = m2 ^ b;
    uint16_t f = m3 ^ c;

    i16vec4 vd = m5 ^ va;
    u16vec4 ve = m6 ^ vb;
    u16vec4 vf = m7 ^ vc;

    int16_t  g = m1 | d;
    uint16_t h = m2 | e;
    uint16_t i = m3 | f;

    i16vec4 vg = m5 | vd;
    u16vec4 vh = m6 | ve;
    u16vec4 vi = m7 | vf;

    u16vec4 vj = ~vi;

    mOut1 = g;
    mOut2 = h;
    mOut3 = i;
    mOut4 = vg;
    mOut5 = vh;
    mOut6 = vj;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
