#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable
#extension GL_AMD_gpu_shader_half_float : enable

layout(set = 0, binding = 0) uniform UBO {
    i16vec4 m1;
    u16vec4 m2;
};

layout(set = 1, binding = 0) buffer SSBO {
    f16vec4 mOut1;
    vec4    mOut2;
    dvec4   mOut3;
};

void main()
{
    mOut1 = f16vec4(m1) + f16vec4(m2);
    mOut2 = vec4(m1) + vec4(m2);
    mOut3 = dvec4(m1) + dvec4(m2);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
