#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable

layout(set = 0, binding = 0) uniform UBO {
    i16vec4 m1;
    i16vec4 m2;
    bvec4   m3;
    u16vec4 m4;
    u16vec4 m5;
    bvec4   m6;
};

layout(set = 1, binding = 0) buffer SSBO {
    i16vec4 mOut1;
    u16vec4 mOut2;
};

void main()
{
    mOut1 = mix(m1, m2, m3);
    mOut2 = mix(m4, m5, m6);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
