#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable
#extension GL_AMD_gpu_shader_half_float : enable

layout(set = 0, binding = 0) uniform UBO {
    f16vec4 m1;
    i16vec4 m2;
    u16vec4 m3;
};

layout(set = 1, binding = 0) buffer SSBO {
    f16vec4 mOut1;
    i16vec4 mOut2;
    u16vec4 mOut3;
};

void main()
{
    mOut1 = int16BitsToFloat16(m2);
    mOut1 = uint16BitsToFloat16(m3);

    mOut2 = float16BitsToInt16(m1);
    mOut3 = float16BitsToUint16(m1);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
