#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable

layout(set = 0, binding = 0) uniform UBO {
    bool  m1;
    bvec4 m2;
};

layout(set = 1, binding = 0) buffer SSBO {
    int16_t  mOut1;
    uint16_t mOut2;
    i16vec4  mOut3;
    u16vec4  mOut4;
};

void main()
{
    mOut1 = int16_t(m1);
    mOut2 = uint16_t(m1);
    mOut3 = i16vec4(m2);
    mOut4 = u16vec4(m2);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
