#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable

layout(set = 0, binding = 0) uniform UBO {
    int16_t m1;
    uint16_t m2;
    i16vec4 m3;
    u16vec4 m4;
};

layout(set = 1, binding = 0) buffer SSBO {
    bool mOut1;
    bool mOut2;
    bvec4 mOut3;
    bvec4 mOut4;
};

void main()
{
    mOut1 = bool(m1);
    mOut2 = bool(m2);
    mOut3 = bvec4(m3);
    mOut4 = bvec4(m4);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
