#version 450 core

#extension GL_EXT_shader_explicit_arithmetic_types_int8: enable

layout(binding = 0) uniform BufIn
{
    int8_t  i8;
    uint8_t u8;

    i8vec2  i8v2;
    u8vec2  u8v2;

    i8vec3  i8v3;
    u8vec3  u8v3;

    i8vec4  i8v4;
    u8vec4  u8v4;

} bufIn;

layout(binding = 1) buffer BufOut
{
    int8_t  i8;
    uint8_t u8;

    i8vec2  i8v2;
    u8vec2  u8v2;

    i8vec3  i8v3;
    u8vec3  u8v3;

    i8vec4  i8v4;
    u8vec4  u8v4;

} bufOut;

void main()
{
    bufOut.i8   = bufIn.i8;
    bufOut.i8v2 = bufIn.i8v2;
    bufOut.i8v3 = bufIn.i8v3;
    bufOut.i8v4 = bufIn.i8v4;
}
// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
