#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable
#extension GL_ARB_gpu_shader_int64 : enable

layout(set = 0, binding = 0) uniform UBO {
    i16vec2 m1;
    i16vec4 m2;
    u16vec2 m3;
    u16vec4 m4;
};

layout(set = 1, binding = 0) buffer SSBO {
    int      mOut1;
    int64_t  mOut2;
    uint     mOut3;
    uint64_t mOut4;
};

void main()
{
    mOut1 = packInt2x16(m1);
    mOut2 = packInt4x16(m2);

    mOut3 = packUint2x16(m3);
    mOut4 = packUint4x16(m4);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
