#version 450 core

#extension GL_EXT_shader_explicit_arithmetic_types_int8: enable

struct Buf
{
    int8_t  i8;
    i8vec2  i8v2;
    i8vec3  i8v3;
    i8vec4  i8v4;

} bufIn;

shared Buf buf[4];

layout(binding = 0) buffer BufOut
{
    i8vec4 i8v4;

} bufOut;

void main()
{
    uint i = gl_GlobalInvocationID.x % 4;

    switch (i)
    {
    case 0:
        bufOut.i8v4.x = buf[i].i8++;
        break;
    case 1:
        bufOut.i8v4.xy = buf[i].i8v2++;
        break;
    case 2:
        bufOut.i8v4.xyz = buf[i].i8v3++;
        break;
    case 3:
        bufOut.i8v4 = buf[i].i8v4++;
        break;
    }
}
// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}} SPIR-V lowering results
; SHADERTEST-COUNT-4: getelementptr [4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }], [4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }] addrspace(3)* @buf, i32 0, i32 %1, i32 {{[0-3]}}
; SHADERTEST-LABEL: {{^// LLPC}} pipeline patching results
; SHADERTEST: load i8, i8 addrspace(3)* getelementptr inbounds ([4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }], [4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }] addrspace(3)* @buf, i32 0, i32 0, i32 0), align 16
; SHADERTEST: store i8 %{{[0-9]*}}, i8 addrspace(3)* getelementptr inbounds ([4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }], [4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }] addrspace(3)* @buf, i32 0, i32 0, i32 0), align 16
; SHADERTEST-COUNT-3: load <{{[2-4]}} x i8>, <{{[2-4]}} x i8> addrspace(3)* getelementptr inbounds ([4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }], [4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }] addrspace(3)* @buf, i32 0, i32 {{[1-3]}}, i32 {{[1-3]}}), align {{[2|4]}}
; SHADERTEST-COUNT-3: store <{{[2-4]}} x i8> %{{[0-9]*}}, <{{[2-4]}} x i8> addrspace(3)* getelementptr inbounds ([4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }], [4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }] addrspace(3)* @buf, i32 0, i32 {{[1-3]}}, i32 {{[1-3]}}), align {{[2|4]}}
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
