#version 450 core
#extension  GL_EXT_device_group : enable

layout(local_size_x = 1, local_size_y = 1) in;
layout(set = 0, binding = 0) buffer OUTBLOCK
{
     uint o0;
};

void main()
{
    o0 = gl_DeviceIndex;
}


// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC.*}} SPIR-V lowering results
; SHADERTEST: call i32 @llpc.input.import.builtin.DeviceIndex.i32.i32
; SHADERTEST-LABEL: {{^// LLPC}} final ELF info
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
