#version 450

layout (local_size_x = 16, local_size_y = 16) in;
shared uint sa1[gl_WorkGroupSize.x];

uint g_f;

void main()
{
    sa1[gl_LocalInvocationID.x] = gl_LocalInvocationID.x;
    g_f = sa1[gl_LocalInvocationID.x];

    sa1[3] = gl_LocalInvocationID.x;
    g_f = sa1[4];
}


// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
