#version 450

layout(local_size_x = 8) in;

shared int  imem;
shared uint umem[4];

layout(binding = 0) uniform Uniforms
{
    int   idata;
    uint  udata;

    int index;
};

uvec4 u4;

void main()
{
    int i1  = 0;
    uint u1 = 0;

    switch (gl_LocalInvocationID.x)
    {
    case 0:
        i1 = atomicAdd(imem, idata);
        u1 = atomicAdd(umem[1], udata);
        break;
    case 1:
        i1 = atomicMin(imem, idata);
        u1 = atomicMin(umem[0], udata);
        break;
    case 2:
        i1 = atomicMax(imem, idata);
        u1 = atomicMax(umem[2], udata);
        break;
    case 3:
        i1 = atomicAnd(imem, idata);
        u1 = atomicAnd(umem[3], udata);
        break;
    case 4:
        i1 = atomicOr(imem, idata);
        u1 = atomicOr(umem[index], udata);
        break;
    case 5:
        i1 = atomicXor(imem, idata);
        u1 = atomicXor(umem[index], udata);
        break;
    case 6:
        i1 = atomicExchange(imem, idata);
        u1 = atomicExchange(umem[index], udata);
        break;
    case 7:
        i1 = atomicCompSwap(imem, 28, idata);
        u1 = atomicCompSwap(umem[index], 17u, udata);
        break;
    }

    u4[i1 % 4] = u1;
}
// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
