#version 450 core

layout(set = 0, binding = 0,  r32i) uniform restrict iimage2D img1;
layout(set = 0, binding = 1,  r32i) uniform coherent iimage2D img2;
layout(set = 0, binding = 2,  r32i) uniform volatile iimage2D img3;

void main()
{
    imageAtomicAdd(img1, ivec2(5, 5), 9);
    imageAtomicAdd(img2, ivec2(5, 5), 9);
    imageAtomicAdd(img3, ivec2(5, 5), 9);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
