#version 450 core

layout(set = 0, binding = 0, r32i)  uniform iimage2D iImg;
layout(set = 0, binding = 1, r32ui) uniform uimage2D uImg;
layout(set = 0, binding = 2, r32f)  uniform image2D  fImg;

layout(set = 1, binding = 0) buffer BO
{
    int   m1;
    uint  m2;
    float m3;
};

void main()
{
    int  temp   = 0;
    uint utemp  = 0;
    float ftemp = 0.f;
    temp += imageAtomicAdd(iImg, ivec2(7, 7), 9);
    temp += imageAtomicMin(iImg, ivec2(7, 7), 9);
    temp += imageAtomicMax(iImg, ivec2(7, 7), 9);
    temp += imageAtomicAnd(iImg, ivec2(7, 7), 9);
    temp += imageAtomicOr(iImg, ivec2(7, 7), 9);
    temp += imageAtomicXor(iImg, ivec2(7, 7), 9);
    temp += imageAtomicExchange(iImg, ivec2(7, 7), 9);
    temp += imageAtomicCompSwap(iImg, ivec2(7, 7), 8, 9);

    utemp += imageAtomicAdd(uImg, ivec2(7, 7), 9u);
    utemp += imageAtomicMin(uImg, ivec2(7, 7), 9u);
    utemp += imageAtomicMax(uImg, ivec2(7, 7), 9u);
    utemp += imageAtomicAnd(uImg, ivec2(7, 7), 9u);
    utemp += imageAtomicOr(uImg, ivec2(7, 7), 9u);
    utemp += imageAtomicXor(uImg, ivec2(7, 7), 9u);
    utemp += imageAtomicExchange(uImg, ivec2(7, 7), 9u);
    utemp += imageAtomicCompSwap(uImg, ivec2(7, 7), 8u, 9u);

    ftemp += imageAtomicExchange(fImg, ivec2(7, 7), 9.0f);

    m1 = temp;
    m2 = utemp;
    m3 = ftemp;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s

; SHADERTEST-LABEL: {{^// LLPC}} SPIR-V lowering results
; SHADERTEST: call i32 @llpc.image.atomiciadd.i32.2D.
; SHADERTEST: call i32 @llpc.image.atomicsmin.i32.2D.
; SHADERTEST: call i32 @llpc.image.atomicsmax.i32.2D.
; SHADERTEST: call i32 @llpc.image.atomicand.i32.2D.
; SHADERTEST: call i32 @llpc.image.atomicor.i32.2D.
; SHADERTEST: call i32 @llpc.image.atomicxor.i32.2D.
; SHADERTEST: call i32 @llpc.image.atomicexchange.i32.2D.
; SHADERTEST: call i32 @llpc.image.atomiccompexchange.i32.2D.
; SHADERTEST: call i32 @llpc.image.atomiciadd.u32.2D.
; SHADERTEST: call i32 @llpc.image.atomicumin.u32.2D.
; SHADERTEST: call i32 @llpc.image.atomicumax.u32.2D.
; SHADERTEST: call i32 @llpc.image.atomicand.u32.2D.
; SHADERTEST: call i32 @llpc.image.atomicor.u32.2D.
; SHADERTEST: call i32 @llpc.image.atomicxor.u32.2D.
; SHADERTEST: call i32 @llpc.image.atomicexchange.u32.2D.
; SHADERTEST: call i32 @llpc.image.atomiccompexchange.u32.2D.
; SHADERTEST: call float @llpc.image.atomicexchange.f32.2D.

; SHADERTEST-LABEL: {{^// LLPC}} pipeline patching results
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.add.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.smin.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.smax.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.and.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.or.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.xor.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.swap.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.cmpswap.2d.i32.i32(i32 9, i32 8, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.add.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.umin.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.umax.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.and.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.or.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.xor.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.swap.2d.i32.i32(i32 9, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.cmpswap.2d.i32.i32(i32 9, i32 8, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0
; SHADERTEST: call i32 @llvm.amdgcn.image.atomic.swap.2d.i32.i32(i32 1091567616, i32 7, i32 7, <8 x i32> %{{[0-9]*}}, i32 0

; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
