#version 450 core

layout(set = 0, binding = 0 ) uniform sampler2DMS       samp2DMS;
layout(set = 0, binding = 1 ) uniform sampler2DMSArray  samp2DMSA;

layout(set = 1, binding = 0) buffer BO
{
    int mOut;
};

void main()
{
    int temp = 0;

    temp += textureSamples(samp2DMS);
    temp += textureSamples(samp2DMSA);

    mOut = temp;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
