#version 450 core

layout(set = 0, binding = 0 ) uniform sampler1D samp1D;
layout(set = 0, binding = 1 ) uniform sampler1D samp1D_2;
layout(set = 0, binding = 1 ) uniform sampler2D samp2D;
layout(set = 0, binding = 2 ) uniform sampler3D samp3D;
layout(set = 0, binding = 3 ) uniform samplerCube sampCube;
layout(set = 0, binding = 4 ) uniform sampler1DArray samp1DA;
layout(set = 0, binding = 5 ) uniform sampler2DArray samp2DA;
layout(set = 0, binding = 6 ) uniform samplerCubeArray sampCubeA;
layout(set = 0, binding = 7 ) uniform sampler1DShadow samp1DS;
layout(set = 0, binding = 8 ) uniform sampler2DShadow samp2DS;
layout(set = 0, binding = 9 ) uniform samplerCubeShadow sampCubeS;
layout(set = 0, binding = 10) uniform sampler1DArrayShadow samp1DAS;
layout(set = 0, binding = 11) uniform sampler2DArrayShadow samp2DAS;
layout(set = 0, binding = 12) uniform samplerCubeArrayShadow sampCubeAS;

layout(set = 1, binding = 0) buffer BO
{
    int mOut;
};

void main()
{
    int temp = 0;

    temp += textureQueryLevels(samp1D);
    temp += textureQueryLevels(samp1D_2);
    temp += textureQueryLevels(samp2D);
    temp += textureQueryLevels(samp3D);
    temp += textureQueryLevels(sampCube);
    temp += textureQueryLevels(samp1DA);
    temp += textureQueryLevels(samp2DA);
    temp += textureQueryLevels(sampCubeA);
    temp += textureQueryLevels(samp1DS);
    temp += textureQueryLevels(samp2DS);
    temp += textureQueryLevels(sampCubeS);
    temp += textureQueryLevels(samp1DAS);
    temp += textureQueryLevels(samp2DAS);
    temp += textureQueryLevels(sampCubeAS);

    mOut = temp;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
