#version 450 core

layout(set = 0, binding = 0, rgba8) uniform image2DMS img2DMS;
layout(set = 0, binding = 1, rgba8) uniform image2DMSArray img2DMSArray;

layout(set = 1, binding = 0) buffer BO
{
    vec4 mIn;
};

void main()
{
    imageStore(img2DMS, ivec2(0, 0), 1, mIn);
    imageStore(img2DMSArray, ivec3(0, 0, 0), 1, mIn);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
