#version 450 core

layout(set = 0, binding = 0, rg16) uniform imageBuffer img2D;

layout(set = 0, binding = 1) buffer BO
{
    vec4 mOut;
};

void main()
{
    vec4 temp1 = imageLoad(img2D, 3);
    mOut = temp1;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
