#version 450 core

layout(set = 0, binding = 0, rgba8) uniform imageCube imgCube;
layout(set = 0, binding = 1, rgba8) uniform imageCubeArray imgCubeArray;

layout(set = 1, binding = 0) buffer BO
{
    vec4 mOut;
};

void main()
{
    vec4 temp1 = imageLoad(imgCube, ivec3(0, 0, 6));
    vec4 temp2 = imageLoad(imgCubeArray, ivec3(0, 0, 6));
    mOut = temp1 + temp2;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
