#version 450
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 1, binding = 4, r11f_g11f_b10f) uniform writeonly image2D _1198;
layout(set = 1, binding = 5, r8) uniform writeonly image2D _1206;

void main()
{
    imageStore(_1198, ivec2(gl_GlobalInvocationID.xy), vec4(1));
    imageStore(_1206, ivec2(gl_GlobalInvocationID.xy), vec4(0));
}


// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
