#version 450 core

layout(set = 0, binding = 0, rgba8i)  uniform iimage2D img2Di;
layout(set = 0, binding = 1, rgba8ui) uniform uimage2D img2Du;

layout(set = 1, binding = 0) buffer BO
{
    vec4 mOut;
};

void main()
{
    ivec4 temp1 = imageLoad(img2Di, ivec2(0, 0));
    uvec4 temp2 = imageLoad(img2Du, ivec2(0, 0));
    mOut = vec4(temp1 + temp2);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
