#version 450 core

layout(set = 0, binding = 0, rgba8) uniform image2D img2D;
layout(set = 0, binding = 1, rgba8) uniform image1D img1D;
layout(set = 0, binding = 2, rgba8) uniform image3D img3D;
layout(set = 0, binding = 3, rgba8) uniform image1DArray img1DArray;
layout(set = 0, binding = 4, rgba8) uniform image2DArray img2DArray;
layout(set = 0, binding = 5, rgba8) uniform image2DRect img2DRect;

layout(set = 1, binding = 0) buffer BO
{
    vec4 mIn;
};

void main()
{
    imageStore(img2D,        ivec2(0, 0), mIn);
    imageStore(img1D,        0, mIn);
    imageStore(img3D,        ivec3(0, 0, 0), mIn);
    imageStore(img1DArray,   ivec2(0, 0), mIn);
    imageStore(img2DArray,   ivec3(0, 0, 0), mIn);
    imageStore(img2DRect,    ivec2(0, 0), mIn);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
