#version 450 core
#extension GL_AMD_shader_image_load_store_lod : enable

layout(set = 0, binding = 0,  r32i) uniform iimage1D        img1D;
layout(set = 0, binding = 1,  r32i) uniform iimage2D        img2D;
layout(set = 0, binding = 2,  r32i) uniform iimage3D        img3D;
layout(set = 0, binding = 3,  r32i) uniform iimageCube      imgCube;
layout(set = 0, binding = 4,  r32i) uniform iimage1DArray   img1DArray;
layout(set = 0, binding = 5,  r32i) uniform iimage2DArray   img2DArray;
layout(set = 0, binding = 6,  r32i) uniform iimageCubeArray imgCubeArray;

void main()
{
    ivec4 temp = ivec4(0);
    temp += imageLoadLodAMD(img1D,          9,              7);
    temp += imageLoadLodAMD(img2D,          ivec2(9, 9),    7);
    temp += imageLoadLodAMD(img3D,          ivec3(9, 9, 9), 7);
    temp += imageLoadLodAMD(imgCube,        ivec3(9, 9, 9), 7);
    temp += imageLoadLodAMD(img1DArray,     ivec2(9, 9),    7);
    temp += imageLoadLodAMD(img2DArray,     ivec3(9, 9, 9), 7);
    temp += imageLoadLodAMD(imgCubeArray,   ivec3(9, 9, 9), 7);

    imageStoreLodAMD(img1D,          9,              7, temp);
    imageStoreLodAMD(img2D,          ivec2(9, 9),    7, temp);
    imageStoreLodAMD(img3D,          ivec3(9, 9, 9), 7, temp);
    imageStoreLodAMD(imgCube,        ivec3(9, 9, 9), 7, temp);
    imageStoreLodAMD(img1DArray,     ivec2(9, 9),    7, temp);
    imageStoreLodAMD(img2DArray,     ivec3(9, 9, 9), 7, temp);
    imageStoreLodAMD(imgCubeArray,   ivec3(9, 9, 9), 7, temp);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
